version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo Hello"
  
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo World"
    
  print_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo $NAME"

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires: 
            - print_hello
      - print_name
